name: run training

on:
  push:
    branches:
      master
    paths:
    - '**.py'
    - 'requirements.txt'
    - '!get_logs.py'
    - '**.json'
    - '**.yml'

jobs:
  build-and-register:
    runs-on: ubuntu-latest

    steps:
    # checkout the repo
    - uses: actions/checkout@master

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Setup Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    
    - name: Install MLflow
      shell: bash
      run: |
        pip install azureml-mlflow

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r 'code/Iris_pytorch/requirements.txt'

    - name: 'Get or Create Workspace'
      run: |
        python 'code/Iris_pytorch/set_workspace.py' --subscription-id ${{ secrets.SUBSCRIPTION_ID }} --workspace-name ${{ secrets.WORKSPACE_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP }} --location ${{ secrets.LOCATION }} 
    
    - name: Create or Load Azure Machine Learning Compute
      run: |
        python 'code/Iris_pytorch/set_computecluster.py'
    
    - name: Configure MLflow with AzureML
      run: |
        python 'code/Iris_pytorch/run_training.py'
    
    - name: Register model 
      run: |
        python 'code/Iris_pytorch/register_model.py'
    
    # - name: Deploy model
    #   run: |
    #     python 'code/Iris_pytorch/deploy_model.py'